/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://qlvwows7obep7ajsf7vukhszxm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-iikvczuokbel7afiedzqpcmtna",
    "aws_cloud_logic_custom": [
        {
            "name": "instagramapi",
            "endpoint": "https://a6qnt91ii3.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:ded36356-da5d-499b-a107-4c0f11706094",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_W9Pu8PucF",
    "aws_user_pools_web_client_id": "79u7qc8jt7297f02qimpk3jsrn",
    "oauth": {
        "domain": "eh77k25oh03h-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.ailenhairstylist.com/",
        "redirectSignOut": "https://www.ailenhairstylist.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ailen-hair-stylist-2-storage-db7b9f38120828-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
